server:
  port: 9048
spring:
  application:
    name: day-gateway
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        # \u914D\u7F6E\u6587\u4EF6\u7684\u540E\u7F00
        file-extension: yml
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: '*'
            allowedMethods: '*'
            allowedHeaders: '*'
            allowCredentials: true
            max-age: 3600
      default-filters:
        - DedupeResponseHeader=Vary Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      discovery:
        locator:
          enabled: true
      routes:
        - id: day-today
          uri: lb://day-today
          predicates:
            - Path=/day-today/**
        - id: day-yesday
          uri: lb://day-yesday
          predicates:
            - Path=/day-yesday/**
# \u65E5\u5FD7\u914D\u7F6E
logging:
  config: classpath:logback-spring.xml
  level:
    com.day.gateway: debug
# 聚合swagger文档
knife4j:
  gateway:
    enable: true