spring:
  cloud:
    nacos:
      server-addr: 172.23.237.39:12848
      #        group: DEV_GROUP  #默认是  DEFAULT_GROUP
      #        namespace: 2f942653-3980-418d-95ed-f36cd44ac984   #默认是public 如果需要使用，则需要将nacos中所创建出来的命名空间中命名空间ID
      discovery:
        server-addr: ${spring.cloud.nacos.server-addr}
        group: APPLICATION
      #        group: DEV_GROUP  #默认是  DEFAULT_GROUP
      #        namespace: 2f942653-3980-418d-95ed-f36cd44ac984   #默认是public 如果需要使用，则需要将nacos中所创建出来的命名空间中命名空间ID
      config:
        import-check:
          enabled: false
        server-addr: ${spring.cloud.nacos.server-addr}
#days:
#  gateway:
#    info: 此处是本地配置文件
#    message: 应用名称是->+${spring.application.name}